### ISSUE TITLE
[FEATURE] Option to wrap lines at current screen width not only 80 characters

### ISSUE THREAD

**Issue by jonvel** [bengarrett/RetroTxt#100]
**Is your feature request related to a problem? Please describe.**
No - this would be a feature enhancement, but is related to issue https://github.com/bengarrett/RetroTxt/issues/64 and https://github.com/bengarrett/RetroTxt/issues/48

**Describe the solution you'd like**
I would like to allow the application to wrap not only at 80 columns, but for however many columns the existing browser window can display.

**Additional context**
Our log files from CI tooling outputs plenty of colorized text, and I use this plugin to help keep my sanity.  Unfortunately, the only two options I have available with RetroText is:
1. wrap at 80 columns
1. not wrap at all.

I'd like to suggest that the option to wrap at "screen width" be included, as well.  Perhaps as a 3 way toggle in the information header (nowrap, 80 column, page width)

**Comment by bengarrett** [comment]
Thanks for the suggestion Jonvel, this feature is complete and will in the next release.

The existing 80 columns wrap locks in an 80 character limit regardless of content.

![Screenshot_2020-10-07  ··  retrotxt com test long-string ans(1)](https://user-images.githubusercontent.com/513842/95289248-07088100-08b6-11eb-99f2-326e4164e98a.png)

The page wrap functionality uses CSS on the `<pre>` tags to wrap the ANSI text to the page, broken by word.

![Screenshot_2020-10-07  ··  retrotxt com test long-string ans](https://user-images.githubusercontent.com/513842/95288565-5cdc2980-08b4-11eb-975f-788f8b0fe107.png)

And it will be found under its own configuration toggle. As the 80 columns wrap and this feature behave differently so there might be a case where someone wants both enabled.

![Screenshot from 2020-10-07 15-41-13](https://user-images.githubusercontent.com/513842/95288766-e5f36080-08b4-11eb-9f0b-57abd51f2e63.png)
