### ISSUE TITLE
[BUG] Multiple line SAUCE comments

### ISSUE THREAD

**Issue by bengarrett** [bengarrett/RetroTxt#106]
**Describe the bug**
SAUCE comments are ignored in 'terminal colloquy' by 'alpha king' of sauna.

**To Reproduce**
Download: https://16colo.rs/pack/thesauna01/ak67-terminal-colloquy.ans
Load: `file:///home/ben/Downloads/ak67-terminal-colloquy.ans`

**RetroTxt (access Options and click the about tab)**
- Version 4

![Screenshot_2020-10-29  ··  ak67-terminal-colloquy ans](https://user-images.githubusercontent.com/513842/97510039-fbe9d200-19d7-11eb-8ecb-19f662301d9b.png)

**Comment by bart-d** [comment]
there are some issues with the SAUCE comments in this very specific file: the commentlines contain newlines and the number of comments is not correctly set (a float in stead of an integer, not properly rounded either). cfr the discussion at https://github.com/16colo-rs/16c/issues/67

Just to point out that it's not necessarily a bug in RetroTxt

**Comment by bengarrett** [comment]
Okay, thanks!

**Comment by bengarrett** [comment]
Fixed, used CSS `white-space: pre-wrap;` to handle unexpected newline characters in the comments.
