### ISSUE TITLE
[BUG] Error when viewing local PDF in browser

### ISSUE THREAD

**Issue by Keith94** [bengarrett/RetroTxt#116]
**Describe the bug**
Red banner "RetroTxt has run into a problem"

**To Reproduce**
1. Open local PDF

**Screenshots**

**RetroTxt (access Options and click the about tab)**
- Version 4.0.3

**Browser (please complete the following information):**
 - OS: Win10
 - Browser Edge Canary

**Additional context**
```
retrotxt.js:61 this.rawText element is missing
DOM @ retrotxt.js:61
retrotxt.js:61 this.rawText element is missing
DOM @ retrotxt.js:61
functions.js:195 Error: RetroTxt failed to load and has been aborted. Were you trying to load an empty file?
    at CheckError (functions.js:193)
    at Execute (retrotxt.js:2276)
    at <anonymous>:1:1
CheckError @ functions.js:195
retrotxt.js:61 this.rawText element is missing
DOM @ retrotxt.js:61
functions.js:1216 could not change the font, dom className is undefined
swap @ functions.js:1216
retrotxt.js:576 this.rawText element is missing
clickLineHeight @ retrotxt.js:576
retrotxt.js:432 Uncaught (in promise) TypeError: Cannot read property 'classList' of undefined
    at DOM.clickTextPairs (retrotxt.js:432)
    at DOM._restoreTextPairs (retrotxt.js:739)
    at DOM.restore (retrotxt.js:669)
    at retrotxt.js:94
retrotxt.js:384 Uncaught (in promise) TypeError: Cannot read property 'classList' of undefined
    at DOM.clickCenterAlign (retrotxt.js:384)
    at DOM._restoreCenterAlign (retrotxt.js:692)
    at DOM.restore (retrotxt.js:663)
    at retrotxt.js:94
functions.js:1543 Uncaught (in promise) TypeError: dom.classList is not iterable
    at ToggleTextEffect (functions.js:1543)
    at DOM._restoreRender (retrotxt.js:731)
    at DOM.restore (retrotxt.js:668)
    at retrotxt.js:94
```

**Comment by bengarrett** [comment]
Hi Keith,

Thanks for submitting this report.

I cannot seem to recreate this issue on Edge `Version 89.0.774.0 (Official build) canary (64-bit)`. RetroTxt should never trigger with local files that have the `.pdf` file extension.

* Does your PDF use the `.pdf` file extension in its filename?
* Is the RetroTxt Setting under _Use RetroTxt as a local text file viewer_, enabled or disabled?


![Capture](https://user-images.githubusercontent.com/513842/105541972-b590de80-5d4c-11eb-8fcf-1efc158a6e74.PNG)

**Comment by Keith94** [comment]
1. Yes it does have .PDF extension
2. Yes it's enabled

**Comment by bengarrett** [comment]
The problem is that this is an issue that's happening for you in a Canary release of the browser, which is the feature equivalent of alpha software. So it could be a problem on the browser that will or has already been fixed.

> Microsoft Edge Canary is the cutting edge development version of the web browser, similarly to how Chrome Canary is the cutting edge version of Google's web browser. Features land in Edge Canary first before they are pushed to Beta and then eventually to Stable versions of the browser.

**Comment by bengarrett** [comment]
Will wait until the stable release of Edge v89 to see if it is an issue.

**Comment by Keith94** [comment]
I think it was fixed in an update. Not seeing the bug anymore.
