### ISSUE TITLE
[BUG] The add-on could not be verified as the add-on manifest file is invalid.

### ISSUE THREAD

**Issue by Keith94** [bengarrett/RetroTxt#149]
Happens after clicking "Get" on Microsoft Store page!

![image](https://user-images.githubusercontent.com/5490615/192860518-c0ca24de-6b3a-46f1-a3cb-0fe979a284eb.png)

**Comment by bengarrett** [comment]
Hi Keith94. Can you check what version of Edge you're using?

It's under ... > Help & Feedback > About Microsoft Edge.

It requires 106+.

I have a feeling the Microsoft Edge Add-ons site is incorrectly giving you the new version of RetroTxt even though it's incompatible with Edge v105.

**Comment by Keith94** [comment]
Yep I am running v105. I guess I will wait for it to update.

**Comment by bengarrett** [comment]
The Edge release schedule says it should be updated sometime soon.

> Week of 29-Sep-2022

**Comment by Keith94** [comment]
I got the chrome version instead, so everything is working.
