### ISSUE TITLE
RetroTxt for Firefox is still 4.2.1

### ISSUE THREAD

**Issue by darkred** [bengarrett/RetroTxt#163]
I see in the RetroTxt [AMO](https://addons.mozilla.org/en-US/firefox/addon/retrotxt/versions/) that the latest version is still 4.2.1, dated Oct 16, 2022 .
But, there have been two releases since then, April's 5.1.0 and today's 5.2.0 (see [Releases](https://github.com/bengarrett/RetroTxt/releases)).

I don't see any failed workflows in [Actions](https://github.com/bengarrett/RetroTxt/actions), so I thought to bring this to your attention.

Also, here are some probably related issues: #45, #69 .

Thank you.

**Comment by bengarrett** [comment]
Hi, thanks for the heads up. Unfortunately, the Firefox edition is stale at the moment.

Essentially, Google rushed to discontinue version 2 of the Extensions API in Chrome (and in Edge, etc). In RetroTxt v5, I migrated the code over to API version 3. But it isn't backward compatible and Firefox hasn't fully implemented it. 

[There's a note in the RetroTxt readme about this.](https://github.com/bengarrett/RetroTxt#a-legacy-edition-is-available-for-firefox-)

> Firefox support will resume once its [Manifest version 3 implementation reaches general availability](https://blog.mozilla.org/addons/2022/05/18/manifest-v3-in-firefox-recap-next-steps/).

**Comment by bengarrett** [comment]
## Bugzilla tracking

#### [[meta] Deprecate background pages in favor of service workers](https://bugzilla.mozilla.org/show_bug.cgi?id=1578286)

#### [[meta] Background Service Worker for Manifest v3](https://bugzilla.mozilla.org/show_bug.cgi?id=1573659)
