### ISSUE TITLE
Port to Node.js as a command line tool.

### ISSUE THREAD

**Issue by bengarrett** [bengarrett/RetroTxt#19]
Share the source on this repo but keep it as self-contained Node script within a subdirectory. 
But share font resources and CSS?

Strip out all the WebExtension browser functionality. Clone relevant Options menu items into command line options. 

Refactor the RetroTxt files to use _webextension_, _node.js_ or _npm_ naming conventions?

Output could be of 3 ways below, and also to screen, to automatic filename, or user supplied filename.
- Default, self-contained, compressed markup where all CSS, used fonts, etc are embedded into a single HTML5 file.
- Developer, same as above but split out all CSS, fonts assets into separate linked files.
- DIV, outputs the markup into a contained <DIV> or <MAIN>. It will include CSS classes that point to CSS and font assets but not contain links to the files.

**Comment by bengarrett** [comment]
This feature is underway!

![2018-03-23_15-08-20](https://user-images.githubusercontent.com/513842/37811146-67ac84ca-2eac-11e8-8550-924ae18aac79.png)

**Comment by clort81** [comment]
can this be done without node.js?

**Comment by bengarrett** [comment]
@clort81 do you mean with the current web extension? unfortunately no.
