### ISSUE TITLE
Corrupted 'double encoded' NFOs are not displayed properly

### ISSUE THREAD

**Issue by Keith94** [bengarrett/RetroTxt#27]
A certain nfo file doesn't look correct when displayed with RetroTxt, other viewers work fine though.

Download nfo here: http://www.nfohump.com/savenfo.php?id=251021

![firefox_2016-12-02_05-36-58](https://cloud.githubusercontent.com/assets/5490615/20835852/8a0d07ba-b851-11e6-969d-43983b99232d.png)

**Comment by bengarrett** [comment]
Hi @Keith94 thanks for the feedback. It seems the NFO file itself is corrupt as it has been saved twice with different character encodings.

**Comment by bengarrett** [comment]
![2016-12-05_9-30-04](https://cloud.githubusercontent.com/assets/513842/20869759/90358e36-bacd-11e6-95df-5602e37b99e1.png)
![2016-12-05_9-28-55](https://cloud.githubusercontent.com/assets/513842/20869760/9036d228-bacd-11e6-9676-81f48e973f26.png)

Searching [infekt's changelog](https://github.com/syndicodefront/infekt/blob/26aa14326fe71ae0324265e05954b0051d8dca9f/ChangeLog.md) for the term _double encoded_

_Support for double-CP437-encoded NFOs that were additionally encoded as UTF-8 afterwards (see issue 104)_
_Support + detect yet another way of broken encodings that NFOs out there have. It's double-encoded, partly-transliterated CP437_

Another example.
https://www.srrdb.com/download/file/Swap.2016.BDRip.x264-ROVERS/swap.2016.bdrip.x264-rovers.nfo

**Comment by Keith94** [comment]
Interesting findings, I didn't know about that. I simply ran into this problem by accident. :P
