### ISSUE TITLE
Weird behavior when local file is deleted

### ISSUE THREAD

**Issue by Keith94** [bengarrett/RetroTxt#28]
Steps to reproduce:

1. Open any local .NFO file in a browser tab
2. Move the source file to recycle bin
3. Reload (F5) the tab with the source file

Result: The tab goes into some kind of looping state where the tab label is flickering constantly.

**Comment by bengarrett** [comment]
Hi Keith I can't seem to replicate this. Each time I open a local file, have RetroTxt applied, delete the source (to recycling) and refresh the tab, I receive the browser message _File not found_ in FF and _Your file was not found_ in Chrome.

This is Firefox? Does this happen with a newly opened copy of your browser or after you have used it for a while? After the tab flashes could you try typing an different invalid ie `file:///c:/nosuchfile.nfo` and see if it happens to it as well, or is the tab not responsive?

**Comment by Keith94** [comment]
Oops, it seems this bug is specific to multi-process feature of Firefox, not related to RetroTxt as I thought it was. My bad!
