### ISSUE TITLE
Split encoding in Chrome

### ISSUE THREAD

**Issue by bengarrett** [bengarrett/RetroTxt#34]
Chrome has this strange bug where it swaps document.characterSet in the middle of the document.

In this example it swaps between _ISO-8859-5_ and _Windows-1252_
`titan-artpack3/ascii/iks&2m-konami.ans`

![2017-03-01_11-50-49](https://cloud.githubusercontent.com/assets/513842/23441286/9127f69e-fe75-11e6-9c5c-eeda3529572f.png)
![2017-03-01_11-50-18](https://cloud.githubusercontent.com/assets/513842/23441285/912747b2-fe75-11e6-8f54-bec90529a737.png)

**Comment by bengarrett** [comment]
Example file, use `file:///` to view in Chrome
[iks&2m-konami.txt](https://github.com/bengarrett/RetroTxt/files/817986/iks.2m-konami.txt)

![notepad](https://cloud.githubusercontent.com/assets/513842/23570287/a60d8576-00b7-11e7-95b5-711b955bfed2.png)
![chrome](https://cloud.githubusercontent.com/assets/513842/23570286/a60cc51e-00b7-11e7-9d71-8bb2bdb88e25.png)

**Comment by bengarrett** [comment]
Submitted issue: https://bugs.chromium.org/p/chromium/issues/detail?id=698605

**Comment by dreamlayers** [comment]
Chrome's encoding guessing seems to be a general nuisance for this extension, even when it's not switching encodings in the middle of a document. One NFO I tried gets autodetected as CP1251 and messed up by that. It is actually plain CP437 which can be viewed using the type command in DOSBox, and needs no transformation. I don't see how to change Chrome's auto-detection. Apparently [they removed the ability to change encodings](https://superuser.com/questions/1160003/how-do-i-change-the-character-encoding-for-a-webpage-in-chrome).

I suppose web server configuration could fix this by specifying an encoding, but it would be nice to not depend on that.

**Comment by bengarrett** [comment]
I feel that the browsers only use the server supplied encoding as a guide. I've found their internal mechanisms will often override server supplied encoding. A large number of ANSI text files for example are treated as binary files and are not viewable in a browser tab. Often the same ANSI file will be handled differently depending on the browser engine.

**Comment by bengarrett** [comment]
Fixed in Chrome
