### ISSUE TITLE
ECMA-48 detection bug

### ISSUE THREAD

**Issue by regentov** [bengarrett/RetroTxt#38]
test/example_files/ecma-48.txt says:
The start of the file MUST begin with an ECMA-48 escape sequence.

Could not find the requirement in standard (http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-048.pdf)

Moreover, if the file does not begin with an escape sequence, there is no way to view it coloured in RetroTxt.

Steps to reproduce: erase the first [0; from test/example_files/ecma-48.txt and see the ugly unformatted text.

Correct behaviour: There should be some way to force ECMA-48 coloring of the file that does not begin with an escape sequence.

**Comment by bengarrett** [comment]
Hi the ecma-48 text stating that requirement is incorrect. There is actually a bug with the ECMA-48 detection.

Line _283_ in `functions.js` has whitespace that shouldn't be there. 
```
c = s.indexOf(`${String.fromCharCode(27)} ${String.fromCharCode(91)} `)
```

needs to be 

```
c = s.indexOf(`${String.fromCharCode(27)}${String.fromCharCode(91)}`)
```

**Comment by bengarrett** [comment]
@regentov Thanks for letting me know about this bug! It has been fixed and submitted to the Chrome store.
