### ISSUE TITLE
Use system fixed width font by default

### ISSUE THREAD

**Issue by ssbarnea** [bengarrett/RetroTxt#43]
I think that it would be better if the defaults settings would be to use system fixed width font instead of using other fonts.

My need is to be able to parse console logs what have coloring (saved with `tee`) and the best user experience would be if it would be as close as possible to the rendering mode of the text files in the browser, just to convert ANSI escapes to HTML tags, nothing more.

**Comment by bengarrett** [comment]
Hi, thanks for the suggestion. I never thought about that as a use case. In the next update, I'll add an option to use the browser default monospace font.

```(css)
.font-monospace {
    font-family: monospace;
}
```

**Comment by bengarrett** [comment]
Oh, I forgot, in the mean time, maybe the most suitable font for your use is the **ISO 9px**. It was created by IBM for their PS/2 line of computers.

**Comment by ssbarnea** [comment]
Thank you! Also please be sure that you make this option the default one. It would be very hard to "sell"(promote) the extension to others if the default settings are awkward. 

My use case is bit different than yours, in my case people do want to **read console logs inside the browser**, usually from the build system. Until now we had to strip ANSI or to use server side ansi2html processing (which generates huge HTML files). 

If we can make the browser deal with ANSI, the overall user experience will clearly improve.

**Comment by bengarrett** [comment]
This request has been implemented and will be in the next update.

The default font suggestion isn't in as it goes against the spirit of the extension. That is to view ANSI and ASCII art which needs MS-DOS era fix-fonts.

But there is a new option in the context menu to set the browser font. It only has to be done once and is very easy to access as shown below. A simple right-click on any active browser tab, select **RetroTxt** and then **Terminal black** or **Terminal white**. The colours switch the background colour.

![terminal-font-selection](https://user-images.githubusercontent.com/513842/30511533-6458eb8c-9b1e-11e7-86f9-4b67117fbecf.png)
