### ISSUE TITLE
ANSI: Add the ability to disable automatic 80 column line wrap

### ISSUE THREAD

**Issue by adi2004** [bengarrett/RetroTxt#48]
Is it possible to have a different screen width? I want to see my Jenkins console without the text going on the second line.

**Comment by bengarrett** [comment]
Hi,
When you view the page/text in-browser without RetroTxt. Does the text get formatted with the same line breaks?

**Comment by bengarrett** [comment]
Okay thanks.

I see the problem. When RetroTxt encounters ANSI text without any metadata describing its size. It automatically wraps the text to 80 columns per-line for maximum compatibility with terminal text. The most common default terminal size is 24 lines and 80 columns (characters) per line.

The issue being some ANSI text uses the cursor control for newlines, others like your Jenkins log file use the standard ASCII line feed and/or carriage return while others use a combination of both.

TODO:
* Add a check box to disable line wrap the _Display_ tab under Options. Place it above the _ANSI ICE Colors_ check.

**Comment by bengarrett** [comment]
Done, this option will be in the next release.
