### ISSUE TITLE
Add: A Custom Colour Pair option

### ISSUE THREAD

**Issue by Keith94** [bengarrett/RetroTxt#51]
If you're interested, please add a [Zenburn](http://kippura.org/zenburnpage/)-like theme to the add-on. Looks quite nice IMO.

**Comment by bengarrett** [comment]
Hi Keith,
Could you clarify? As I am not sure where this Vim theme could be applied?

**Comment by Keith94** [comment]
Hey, I was thinking you could add the Zenburn colors as one of the "color pairs" in RetroTxt that users can select? Or is that out of scope? I mean colors that are similar looking to this:

![image](https://user-images.githubusercontent.com/5490615/38155845-8fdac1e2-3469-11e8-8045-35fcc71b371f.png)

**Comment by bengarrett** [comment]
Hard coding that specific theme is probably a little out of scope. It might be more useful to allow a custom Colour Pair choice from the Options menu, which would then prompt for standard RGB or hex values. But maybe I can add a Zenburn-like colour pair as the default 'custom' choice for you :)

**Comment by Keith94** [comment]
That sounds good to me :+1:

**Comment by bengarrett** [comment]
Done, will be included in the next release.

**Comment by Keith94** [comment]
Thanks @bengarrett; when's the new version ready?
