### ISSUE TITLE
Download file endless loop

### ISSUE THREAD

**Issue by bengarrett** [bengarrett/RetroTxt#56]
**Describe the bug**
After a file has completed its download, RT repeatedly tries to download and reopen the download causing an endless loop in Chrome.

**To Reproduce**
1. Make sure _Apply RetroTxt to any downloaded or local text files_ is enabled.
2. Visit https://agenda.com/
3. Click the Download for MacOS button

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 71

**Comment by Keith94** [comment]
Can confirm! I really thought my system had a virus for a second, lol.

**Comment by bengarrett** [comment]
Hi Keith, sorry about that! If you have not done so already, a quick fix is to disable the _Apply RetroTxt to any downloaded or local text files_.

**Comment by bengarrett** [comment]
Fixed, will be patched in the next release.

**Comment by Keith94** [comment]
That's good.
