### ISSUE TITLE
Add aixterm bright colour support

### ISSUE THREAD

**Issue by shalak** [bengarrett/RetroTxt#57]
**Describe the bug**
I'm hoping to use RetroTXT to see colored logs on our CI system, which stores linux terminal output to a .log file.

Unfortunately, my logs are not properly parsed in RetroTXT and I'm wondering what might be the fault.

**To Reproduce**
Open attached file in RetroTXT for Firefox:
[example_broken.txt](https://github.com/bengarrett/RetroTxt/files/2731982/example_broken.txt)

**Expected behavior**
Colored output is shown.

**Screenshots**
Here's what the attached file looks like in terminal. Note that the "INFO" is colored:
![works_in_terminal](https://user-images.githubusercontent.com/1536554/50757767-a2dc0780-1260-11e9-9c1f-8e31497dca34.png)

And there's how it looks in RetroTXT:
![doesnt_work_in_retrotxt](https://user-images.githubusercontent.com/1536554/50757779-a8395200-1260-11e9-9fa2-0b72085e1e8a.png)

**Desktop:**
 - OS: Ubuntu Linux 18.04 LTS
 - Browser Firefox
 - Version 64.0

**Additional context**
Note that when I run simple `ls -althr --color > file.txt`, the colored output is properly shown by RetroTXT, just my logs are non-compatible somehow.

**Comment by bengarrett** [comment]
Hi @shalak, thanks for submitting this.

I took a look at `example-broken.txt` and is using escape sequences that RetroTxt does not recognise.

`ls --color` outputs using standard ANSI sequences. While your logs include sequences such as `␛[97m␛[96m`.

After searching online, the values 90-97 are bright foreground colours, and 100-107 are bright background colours for the IBM AIX terminal. These are non-standard but I guess have migrated over into some Linux tools and shells.

Assuming these codes do not conflict, I can add support for these in the next update.

**Comment by bengarrett** [comment]
See: 
https://unix.stackexchange.com/questions/93814/cant-apply-brightness-to-terminals-background-color/93872#93872

https://en.wikipedia.org/wiki/ANSI_escape_code#3/4_bit

**Comment by shalak** [comment]
FYI: the color codes came from python's `colorama` package and I just noticed that they did warn me about this issue :)
```
$ grep -A 20 'class AnsiFore' colorama/ansi.py 
class AnsiFore(AnsiCodes):
    BLACK           = 30
    RED             = 31
    GREEN           = 32
    YELLOW          = 33
    BLUE            = 34
    MAGENTA         = 35
    CYAN            = 36
    WHITE           = 37
    RESET           = 39

    # These are fairly well supported, but not part of the standard.
    LIGHTBLACK_EX   = 90
    LIGHTRED_EX     = 91
    LIGHTGREEN_EX   = 92
    LIGHTYELLOW_EX  = 93
    LIGHTBLUE_EX    = 94
    LIGHTMAGENTA_EX = 95
    LIGHTCYAN_EX    = 96
    LIGHTWHITE_EX   = 97
```

**Comment by bengarrett** [comment]
Complete, support will be included in the next release.
