### ISSUE TITLE
scanlines

### ISSUE THREAD

**Issue by angea** [bengarrett/RetroTxt#8]
can we have 25% - 50% - 75% scanlines?

**Comment by bengarrett** [comment]
Hi Ange, what do you mean by scan lines, fake CRT black lines on screen?

**Comment by angea** [comment]
yes

**Comment by bengarrett** [comment]
I don't think it can be done it to decent effect. You could create fake scan lines and apply them to the background of the page like this. But it doesn't effect the text overlaid on top of the background.

https://codepen.io/0x04/pen/qlayi

But I may add a checkbox for just 1 style of scan line.

**Comment by bengarrett** [comment]
Done for next release.
