### ISSUE TITLE
[BUG] Downloaded files from srrdb.com are not opened in the browser

### ISSUE THREAD

**Issue by darkred** [bengarrett/RetroTxt#85]
**Describe the bug**
Downloaded files from srrdb.com are not opened in the browser

**To Reproduce**

0. In a fresh Chrome 84 profile with only the extension
1. Go to extension Options, enable `Allow access to file URLs`
and then also enable `Apply RetroTxt to any downloaded or local text files' in the 'Config Options`
2. Open e.g. [this srrdb page](https://www.srrdb.com/release/details/Skater.XL.The.Ultimate.Skateboarding.Game-DARKSiDERS)
3. Click on the 'darksiders.nfo' link (in the 'Stored files' row) to download it
4. The downloaded NFO file doesn't open inside the browser

**RetroTxt (access Options and click the about tab)**
- Version: 3.5.0

**Browser (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: Chrome 
 - Version: 84

Thank you

**Comment by bengarrett** [comment]
Hi, this seems to be a misconfiguration with the web site. Their text files are sent with the `application/octet-stream` binary flagged header which RetroTxt rightly ignores. It only monitors downloads if they're sent with the `text/plain` headers.

**Comment by darkred** [comment]
Thank you for the explanation.
So I reported it to the srrdb issue tracker ( [issue](https://bitbucket.org/srrdb/srrdb-issues/issues/112/retrotxt-extension-downloaded-text-files))
I'm closing it. If/when it's fixed, I'll report here.
