### ISSUE TITLE
Post-processing of web text strippers, Readability, Pocket, Instapaper

### ISSUE THREAD

**Issue by angea** [bengarrett/RetroTxt#9]
I often use Readability to turn a bloated webpage in a single text.
can RetroTXT work to postprocess the output ?

**Comment by bengarrett** [comment]
Hi Ange thanks for the suggestion,

I think it could be possible using the [Readability API](https://www.readability.com/developers/api/parser) but it would require either the user having or the app having API authentication keys. Unfortunately these are capped so probably the user would need to sign up for their own. But I don't know if many people would use it, for the work that would be required to implement it.

The other question would be if Readability is supported, why not Pocket, Instapaper etc? But they all have their own APIs and different ways of accessing their data.

I'll keep this open as a possibility.

**Comment by bengarrett** [comment]
[Moved to Project](https://github.com/bengarrett/RetroTxt/projects/1)
